// One grouped photo attachment, matching the supplied Messages reference.
const albumState={index:0,drag:null,suppressClickUntil:0};
const albumNames=Object.keys(people);
function albumPhoto(name){return profileContent(name);}
function albumMarkup(){return `<div class="photo-album" data-album><button class="album-count" data-album-grid aria-label="View all ${albumNames.length} photos"><span class="album-grid-icon" aria-hidden="true"><i></i><i></i><i></i><i></i></span>${albumNames.length} Photos</button><div class="album-stack" aria-label="Profile photo stack. Swipe or use arrow keys to browse.">${albumNames.map((name,i)=>`<div class="album-item" data-album-index="${i}"><div class="profile album-card shared-profile" data-person="${name}" data-reactable="deck-${name}" tabindex="${i===0?0:-1}" role="button" aria-label="Open ${name}’s photo">${albumPhoto(name)}</div></div>`).join('')}</div></div>`;}
function updateAlbum(){document.querySelectorAll('.album-item').forEach((item,i)=>{const offset=(i-albumState.index+albumNames.length)%albumNames.length;item.dataset.offset=offset;item.style.zIndex=String(albumNames.length-offset);const card=item.querySelector('.album-card');card.tabIndex=offset===0?0:-1;card.setAttribute('aria-hidden',offset!==0);});}
function advanceAlbum(delta){albumState.index=(albumState.index+delta+albumNames.length)%albumNames.length;updateAlbum();syncDeck();announce(albumNames[albumState.index]+', photo '+(albumState.index+1)+' of '+albumNames.length);}
function closeAlbum(){document.querySelector('.album-dialog')?.remove();document.querySelectorAll('#screen-21 .phone [inert]').forEach(x=>x.inert=false);const target=albumState.opener?.isConnected?albumState.opener:document.querySelector('.album-item[data-offset="0"] .album-card');target?.focus({preventScroll:true});}
function openAlbum(mode='photo'){if(!document.querySelector('.album-dialog'))albumState.opener=document.activeElement;document.querySelector('.album-dialog')?.remove();const name=albumNames[albumState.index],dialog=document.createElement('div');dialog.className='album-dialog';dialog.setAttribute('role','dialog');dialog.setAttribute('aria-modal','true');dialog.setAttribute('aria-label',mode==='grid'?'All profile photos':name+' profile photo');dialog.dataset.mode=mode;
 dialog.innerHTML=`${status()}<div class="album-view-nav"><button data-album-close aria-label="Close photos">‹ <span>Messages</span></button><span>${mode==='grid'?`${albumNames.length} Photos`:`${albumState.index+1} of ${albumNames.length}`}</span><button data-album-grid aria-label="View all photos">${icon('<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>')}</button></div>`+(mode==='grid'?`<div class="album-grid">${albumNames.map((n,i)=>`<button data-album-open="${i}" aria-label="Open ${n}’s photo"><img src="assets/${people[n].photo}.jpg" alt=""><b>${n}</b>${showcaseState.hearts.has(n)?'<span aria-label="Hearted">♥</span>':''}</button>`).join('')}</div><p class="album-grid-hint">Tap a photo to take a closer look.</p>`:`<div class="album-view-photo profile shared-profile" data-person="${name}" data-reactable="viewer-${name}" tabindex="0" role="button" aria-label="${name} photo. Hold for Tapbacks">${albumPhoto(name)}</div><div class="album-view-controls"><button data-album-step="-1" aria-label="Previous photo">‹</button><button data-album-step="1" aria-label="Next photo">›</button></div><p class="album-view-hint">Touch and hold the photo to react.</p>`)+home;
 const phone=document.querySelector('#screen-21 .phone');[...phone.children].forEach(x=>x.inert=true);phone.append(dialog);syncDeck();dialog.querySelector('[data-album-close]').focus();}
function albumClick(e){if(performance.now()<albumState.suppressClickUntil&&e.target.closest('[data-album],.album-dialog'))return true;const b=e.target.closest('button');if(b?.hasAttribute('data-album-close')){closeAlbum();return true;}if(b?.hasAttribute('data-album-grid')){openAlbum('grid');return true;}if(b?.hasAttribute('data-album-open')){albumState.index=Number(b.dataset.albumOpen);updateAlbum();openAlbum();return true;}if(b?.dataset.albumStep){const delta=Number(b.dataset.albumStep);advanceAlbum(delta);openAlbum();document.querySelector(`[data-album-step="${delta}"]`).focus();return true;}const card=e.target.closest('.album-item[data-offset="0"] .album-card');if(card&&!b){if(!document.querySelector('.reaction-menu'))openAlbum();return true;}return false;}
document.addEventListener('pointerdown',e=>{if(!e.isPrimary||e.button!==0||!e.target.closest('.album-stack,.album-view-photo'))return;albumState.drag={x:e.clientX,y:e.clientY,id:e.pointerId,viewer:!!e.target.closest('.album-view-photo')};});
document.addEventListener('pointermove',e=>{const d=albumState.drag;if(!d||d.id!==e.pointerId||d.viewer)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.abs(dx)>12&&Math.abs(dx)>Math.abs(dy)){const stack=document.querySelector('.album-stack');stack.classList.add('dragging');stack.style.setProperty('--drag-x',Math.max(-100,Math.min(100,dx))+'px');}});
function endAlbumDrag(e){const d=albumState.drag;if(!d)return;albumState.drag=null;const stack=document.querySelector('.album-stack');stack?.classList.remove('dragging');stack?.style.removeProperty('--drag-x');if(e.type==='pointercancel')return;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.abs(dx)>40&&Math.abs(dx)>Math.abs(dy)){if(d.viewer){advanceAlbum(dx<0?1:-1);openAlbum();}else{dismiss();advanceAlbum(dx<0?1:-1);}albumState.suppressClickUntil=performance.now()+450;}}
document.addEventListener('pointerup',endAlbumDrag);document.addEventListener('pointercancel',endAlbumDrag);
document.addEventListener('keydown',e=>{const dialog=document.querySelector('.album-dialog'),stack=e.target.closest('[data-album]');if(!dialog&&!stack)return;if(document.querySelector('.reaction-menu'))return;if(dialog&&e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();closeAlbum();return;}if((!dialog||dialog.dataset.mode==='photo')&&(e.key==='ArrowLeft'||e.key==='ArrowRight')){e.preventDefault();e.stopImmediatePropagation();advanceAlbum(e.key==='ArrowLeft'?-1:1);if(dialog)openAlbum();else document.querySelector('.album-item[data-offset="0"] .album-card').focus();return;}if(stack&&e.target.matches('.album-card')&&(e.key==='Enter'||e.key===' ')){e.preventDefault();e.stopImmediatePropagation();openAlbum();return;}if(dialog&&e.key==='Tab'){const buttons=[...dialog.querySelectorAll('button')],i=buttons.indexOf(document.activeElement);e.preventDefault();e.stopImmediatePropagation();buttons[(i+(e.shiftKey?-1:1)+buttons.length)%buttons.length].focus();}},true);
