const icon=(body,view='0 0 24 24')=>`<svg viewBox="${view}" width="24" height="24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${body}</svg>`;
const back=icon('<path d="m15 3-9 9 9 9"/>');
const camera=icon('<rect x="2" y="6" width="13" height="12" rx="3"/><path d="m15 10 7-4v12l-7-4"/>');
const mic=icon('<rect x="9" y="2" width="6" height="13" rx="3"/><path d="M6 11v1a6 6 0 0 0 12 0v-1M12 18v4m-3 0h6"/>');
const status=()=>`<div class="status"><span class="time">9:41</span><div class="island"></div><div class="status-icons"><svg width="17" height="13" viewBox="0 0 17 13" fill="currentColor"><rect y="9" width="3" height="4" rx=".8"/><rect x="4.5" y="6" width="3" height="7" rx=".8"/><rect x="9" y="3" width="3" height="10" rx=".8"/><rect x="13.5" width="3" height="13" rx=".8"/></svg><svg width="17" height="13" viewBox="0 0 17 13" fill="none" stroke="currentColor" stroke-width="2.3"><path d="M1 4a12 12 0 0 1 15 0M4 7a7 7 0 0 1 9 0M7 10a2 2 0 0 1 3 0"/></svg><svg width="27" height="13" viewBox="0 0 27 13"><rect x=".5" y=".5" width="23" height="12" rx="3" fill="none" stroke="#999"/><rect x="2.5" y="2.5" width="19" height="8" rx="1.3" fill="#111"/><path d="M25 4v5q3-2.5 0-5" fill="#999"/></svg></div></div>`;
const brand='<img class="brand-image" src="assets/inyo-logo.png" alt="inyo">';
const logo='<div class="avatar">'+brand+'</div>';
const nav=(group=false)=>`<div class="nav"><span class="back">${back}</span>${group?`<div class="group-avatar">${logo}<img src="assets/leo.jpg" alt=""><img src="assets/maya.jpg" alt=""></div>`:logo}<div class="contact">${group?'Maya, Leo & Inyo':'Inyo'} <span class="chevron">›</span></div><span class="video">${camera}</span></div>`;
const composer=()=>`<div class="composer"><span class="plus" aria-hidden="true">${icon('<path d="M12 3v18M3 12h18"/>')}</span><div class="input"><span>iMessage</span><span style="width:15px;transform:scale(.68);transform-origin:top left">${mic}</span></div></div>`;
const home='<div class="home"></div>';
const stamp=(t='Monday 9:41 AM',initial=false)=>`<div class="stamp">${initial?'iMessage<br>':''}${t}</div>`;
let messageId=0;
const msg=(t,out=false,reaction='')=>`<div class="row ${out?'out ':''}tail"><div class="bubble" ${out?'':'tabindex="0" role="button" aria-description="Double-click or hold for reactions"'} data-reactable="m${++messageId}">${t}${reaction?`<span class="tapback" data-owner="${out?'Inyo':'You'}" aria-label="${out?'Inyo':'You'} reacted ${reaction}">${reaction}</span>`:''}</div></div>`;
const read='<div class="read">Read</div>';
const attribution=()=>''; // These are link previews and media, not extension messages.
const webBar=(backTo=2)=>`<div class="web-bar"><button data-go="${backTo}" aria-label="Close session">‹ Messages</button>${brand}<span class="web-lock" aria-hidden="true">${icon('<rect x="6" y="10" width="12" height="10" rx="2"/><path d="M9 10V7a3 3 0 0 1 6 0v3"/>')}</span></div><div class="safari-bar" aria-hidden="true"><span>☷</span><span>joininyo.com</span><span>•••</span></div>`;
const art=()=>'<div class="conversation-art"><div class="art-bubble"><i class="art-dot"></i></div><div class="art-bubble light"></div></div>';
const cover=()=>`<div class="cover game-cover">${eveningArt()}<span class="wordmark">${brand}</span><span class="cover-label">YOUR KIND OF CLOSE</span></div>`;
const sessionCard=()=>`<div class="cardwrap"><a class="session-card" data-go="3" href="#screen-3" aria-label="Open Your kind of close">${cover()}<div class="card-copy"><b>Your kind of close</b><p>Closeness, space, and the things<br>that help you feel met.</p><small class="link-host">joininyo.com</small></div></a>${attribution()}</div>`;
const profileData={
 Leo:{age:24,city:'New York',photo:'leo',intent:'Looking for a relationship',bio:'Room for our own lives. Someone to share the ordinary days with.'},
 Maya:{age:22,city:'New York',photo:'maya',intent:'Looking for a relationship',bio:'Cooking with music on. Long walks that were supposed to be short.'},
 Kai:{age:25,city:'New York',photo:'kai',intent:'Looking for a relationship',bio:'Someone to get to know over dinner and a very long walk.'},
 Ethan:{age:25,city:'Queens',photo:'ethan',intent:'Looking for a relationship',bio:'A Sunday market, something good to cook, and no rush to get home.'},
 Daniel:{age:24,city:'Brooklyn',photo:'daniel',intent:'Looking for a relationship',bio:'A little adventure. Someone to share the ordinary days with.'}
};
function profileContent(person){const p=profileData[person];return `<div class="portrait"><img class="album-image" src="assets/${p.photo}.jpg" alt="Fictional ${person} profile"><img class="photo-logo album-brand" src="assets/inyo-logo-white.png" alt="inyo"></div><div class="profile-meta album-caption"><div><b>${person}, ${p.age}</b><small>${p.intent}</small></div><span>${p.city}</span><p class="profile-bio">${p.bio}</p></div>`;}
const profile=(person,heart=false)=>`<div class="cardwrap profile-wrap"><div class="profile shared-profile" role="button" tabindex="0" aria-label="${person}’s Inyo profile. Hold for reactions" data-person="${person}" data-profile-person="${person}" data-reactable="profile-${person}">${profileContent(person)}</div>${heart?'<span class="heart">♥</span>':''}</div>`;
const receipt=()=>`<div class="cardwrap receipt-wrap row tail"><div class="bubble receipt"><p>Your play is saved.</p></div></div>`;
const chat=(content,{group=false,cls='',extra=''}={})=>`<div class="phone ${cls}">${status()}${nav(group)}<div class="thread">${content}</div>${composer()}${extra}${home}</div>`;
const paths={talk:'<path d="M4 5h23v17H12l-8 7V5Z"/><path d="M10 11h11M10 16h7"/>',sun:'<circle cx="16" cy="16" r="6"/><path d="M16 2v4m0 20v4M2 16h4m20 0h4M6 6l3 3m14 14 3 3M6 26l3-3M23 9l3-3"/>',kite:'<path d="m16 3 12 10-12 10L4 13 16 3Zm0 0v20M4 13h24M16 23c0 7 9 2 8 8"/>',moon:'<path d="M25 22A13 13 0 0 1 11 3a13 13 0 1 0 14 19Z"/>'};
const rounds=[{title:'Set the mood.',prompt:'Pick two things you’d want in the mix. A little space counts too.',limit:2,options:[['Really talking','Time to hear each other.','talk'],['A little affection','Only what feels welcome to both.','sun'],['Something playful','Laughing, making, trying things.','kite'],['Room to myself','Together does not mean all the time.','moon']],chosen:[0,3]},{title:'Find your rhythm.',prompt:'No right amount of texting. What feels good to you?',limit:1,options:[['Small, regular check-ins','A little contact through the day.'],['One proper catch-up','Less often, more present.'],['Flexible, no tally','Not every gap needs explaining.'],['Agree on it together','I want us to talk about the rhythm.']],chosen:[2]},{title:'One thing to keep.',prompt:'Something you’d want closeness to make room for.',limit:1,options:[['My no stays a no',''],['Room for my own life',''],['Direct, kind honesty',''],['Privacy I choose','']],chosen:[2]}];
const scenery=(body,view='0 0 320 150')=>`<svg viewBox="${view}" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">${body}</svg>`;
const eveningArt=()=>worldArt(0);
const postcardPicture=(round,i)=>worldArt(round*2+i);
const planArt=()=>worldArt(2);
function gameStage(kind,round,collection){
 const r=collection[round],chosen=r.chosen.map(i=>r.options[i][0]);
 if(kind==='fit')return fitStage(round,collection);
 if(round===0&&kind!=='future')return composeScene(kind,collection);

 if(kind==='future')return `<div class="postcard-collection" aria-label="Your postcard collection">${collection.map((r,i)=>`<div class="collected ${r.chosen.length?'filled':''}"><span>${r.chosen.length?worldArt(i*2+r.chosen[0]):String(i+1).padStart(2,'0')}</span><b>${['A place','Your people','A little freedom'][i]}</b></div>`).join('')}</div>`;
 if(kind==='friends'&&round===2)return `<div class="game-stage message-stage"><div class="stage-incoming">hey, i’m sorry. can we rain check tonight? 😭</div><div class="stage-outgoing">${chosen[0]||'Your reply…'}</div></div>`;
 if(kind==='close'&&round===1)return `<div class="game-stage rhythm-stage" data-rhythm="${r.chosen[0]??'none'}"><div class="rhythm-clock">A rhythm that fits your life</div><div class="rhythm-dots"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><b>${chosen[0]||'Try a rhythm below'}</b></div>`;
 if(kind==='close'&&round===2)return `<div class="game-stage promise-stage"><span>A LITTLE PROMISE</span><b>${chosen[0]||'What stays yours?'}</b><i>yours to keep ♡</i></div>`;
 if(kind==='friends'&&round===1)return `<div class="game-stage circle-stage" data-entrance="${r.chosen[0]??'none'}"><div class="circle-people"><i>you</i><i>+</i><i>+</i><i>+</i><svg viewBox="0 0 300 70" aria-hidden="true"><path d="M45 39Q90 0 125 39T205 39T275 39" fill="none" stroke="#97aabd" stroke-width="1.5" stroke-dasharray="4 5"/></svg></div><b>${chosen[0]||'There’s a place for you here.'}</b></div>`;
 return `<div class="game-stage illustrated-stage" data-drop-zone aria-label="Your scene. Drop a choice here.">${kind==='friends'?planArt():eveningArt()}<div class="stage-picks">${chosen.length?chosen.map(s=>`<span>${s}</span>`).join(''):'<span>Make it your kind of evening</span>'}</div></div>`;
}
function refreshGame(phone){const kind=phone.dataset.game;if(!kind)return;const collection=kind==='close'?rounds:explorations[kind].rounds;const round=Number(phone.dataset.round),stage=phone.querySelector('.game-stage,.postcard-collection');if(stage)stage.outerHTML=gameStage(kind,round,collection);}

function session(round,collection=rounds,sessionTitle='Your kind of close'){const r=collection[round],kind=sessionTitle==='Postcards from later'?'future':sessionTitle==='Small circle'?'friends':sessionTitle==='Fit check'?'fit':'close';return `<div class="phone expanded game-session" data-game="${kind}" data-round="${round}">${status()}${webBar()}<div class="session-body"><div class="progress">${collection.map((_,i)=>`<i class="${i<=round?'done':''}"></i>`).join('')}</div><div class="round-label">${round?'<button class="round-back" data-round-back aria-label="Previous round">‹</button>':''}${sessionTitle} · ${round+1} of ${collection.length}</div><h2>${r.title}</h2><p>${r.prompt}</p>${gameStage(kind,round,collection)}<div class="choices ${round?'list':''}" role="group" aria-label="Choose ${r.limit===1?'one':'up to '+r.limit}">${r.options.map((o,i)=>`<button class="choice ${r.chosen.includes(i)?'selected':''}" data-choice="${i}" draggable="${!['future','fit'].includes(kind)&&round===0}" aria-pressed="${r.chosen.includes(i)}"><span class="check">✓</span>${kind==='fit'?fitChoiceArt(round,i):sessionTitle==='Postcards from later'?`<span class="postcard-scene scene-${round}-${i}">${postcardPicture(round,i)}</span>`:o[2]?icon(paths[o[2]],'0 0 32 32'):''}<b>${o[0]}</b>${o[1]?`<small>${o[1]}</small>`:''}</button>`).join('')}</div></div><div class="session-actions"><div class="count">${r.chosen.length} of ${r.limit} selected</div><button class="primary" data-next="${round+5}" ${r.chosen.length!==r.limit?'disabled':''}>${round===2?(kind==='fit'?'See my edit':'Finish'):'Next'} <span aria-hidden="true">→</span></button><button class="skip" data-go="${round+5}">Skip this round</button></div>${home}</div>`;}
const sessionLanding=()=>`<div class="phone expanded session-landing">${status()}${webBar()}<div class="landing-content">${brand}<div class="landing-art">${eveningArt()}</div><span class="round-label">A LITTLE ROOM FOR YOU</span><h2>Your kind<br>of close.</h2><p>What makes being with someone feel good?<br>Let’s start with the little things.</p><button class="primary" data-go="4">Let’s play <span aria-hidden="true">→</span></button><small>3 small rounds. Skip anything.</small></div>${home}</div>`;
const pollOption=(label,selected=false)=>`<button class="poll-option ${selected?'chosen':''}" aria-pressed="${selected}"><span class="poll-mark" aria-hidden="true">${selected?'✓':''}</span><span class="poll-label">${label}</span><img class="poll-voter" src="assets/maya.jpg" alt="Your vote"><span class="poll-votes">${selected?'1':''}</span></button>`;
const poll=()=>`<div class="cardwrap native-poll"><div class="poll"><div class="poll-options">${['Coffee + a walk','One drink','Something to do'].map((s,i)=>pollOption(s,i===0)).join('')}</div><button class="poll-add" data-add-choice>Add Choice</button><form class="poll-add-form" hidden><input aria-label="New poll choice" maxlength="60" required placeholder="Add a choice"><button type="submit" aria-label="Send poll choice">↑</button></form></div></div>`;
const audio=()=>`<div class="row tail"><div class="bubble audio"><button class="play" data-voice aria-label="Play sample voice note">▶</button><span class="wave">${Array.from({length:38},(_,i)=>`<i style="height:${5+(i*17%23)}px"></i>`).join('')}</span><small data-voice-time>0:08</small><audio preload="metadata" src="assets/pep-talk.m4a"></audio></div></div>`;
const screens=[
 {title:'You’re already known',note:'After signup · A heart, a brief celebration, and one question grounded in Maya’s cooking interest. Replay the welcome effect.',html:()=>chat(stamp(undefined,true)+msg('hey inyo, i’m in :)',true,'♥')+msg('hey maya!! i’m inyo. <em>nice to meet you!</em>')+'<button class="replay" data-effect="confetti">↻ Replay</button>'+msg('your profile came through :)')+msg('you mentioned cooking. date-night kitchen: someone follows your lead, or you both improvise?')+msg('both improvise. music on. no pressure to keep talking the whole time',true)+msg('being able to be quiet without it getting weird?')+msg('exactly!!',true)+read)},
 {title:'The right moment for a session',note:'A quiet, single-surface message card. The content has room to breathe.',html:()=>chat(stamp('Monday 9:43 AM')+msg('comfortable silence. yes. that’s the thing',true)+msg('okay, i get you now')+msg('i have a little game for this. wanna try?')+msg('yes actually',true)+sessionCard())},
 {title:'A little space to play',note:'A private Inyo web session opens from its link. The Messages return control returns to the invitation.',html:sessionLanding},
 {title:'Closeness, with room for space',note:'Private web session · Choose two. Tap the tiles to change the selection.',html:()=>session(0)},
 {title:'A rhythm that feels good',note:'Private web session · A different interaction density for a single choice.',html:()=>session(1)},
 {title:'What closeness should protect',note:'Private web session · Clear selections, one action, no dashboard or nested cards.',html:()=>session(2)},
 {title:'Back to the conversation',note:'A compact saved receipt. Personal choices stay out of the preview card.',html:()=>chat(stamp('Monday 9:45 AM')+receipt()+msg('really talking, with room for your own life. does that fit?')+msg('yes. i like being close, i just don’t want to text every second',true)+msg('what would you want someone to understand when you go quiet?')+msg('that i’m probably just doing my own thing. not losing interest',true)+msg('so quiet ≠ losing interest. that’s a good thing to know about you')+msg('exactly',true)+read)},
 {title:'Maya meets Leo’s profile',note:'Maya’s view · An edge-to-edge profile image. Double-tap or hold to react.',html:()=>chat(stamp('Thursday 6:12 PM')+msg('leo caught your eye 👀')+profile('Leo')+msg('is he a calls or texts person?',true)+msg('he hasn’t told me yet. you should ask him that lol'))},
 {title:'Ask before the introduction',note:'The agent answers from shared information, then leaves room for the actual conversation.',html:()=>chat(stamp('Thursday 6:13 PM')+msg('got your heart on leo’s card :)')+profile('Leo',true)+msg('yeah, i’d like to meet him',true)+msg('on it. i’ll check with him too'))},
 {title:'Leo gets his own side',note:'Leo’s view · Real indoor photo, distinct setting. The same card design and mutual opt-in.',html:()=>chat(stamp('Thursday 6:18 PM')+msg('<span data-profile-name>maya</span>’s interested in meeting you. here’s her card')+profile('Maya',true)+msg('yeah i’d like to meet her',true)+msg('okay!! i’ll put you two in a chat'))},
 {title:'The introduction has a handoff',note:'Maya’s view · The group exists after both opt in. The agent leaves the next move to them.',html:()=>chat(stamp('Thursday 6:19 PM')+'<div class="speaker">Inyo</div>'+msg('<span data-profile-name>maya</span>, meet leo. leo, meet <span data-profile-name>maya</span> :) you both wanted an intro, so here you are')+'<div class="speaker">Leo</div>'+msg('hey <span data-profile-name>maya</span> :)')+msg('hi! important question: are you a calling person or a texting person',true)+'<div class="speaker">Leo</div>'+msg('texting until the story gets too long to type')+msg('okay this is the correct answer',true)+'<div class="speaker">Leo</div>'+msg('what’s your cutoff? i feel like mine is 3 paragraphs'),{group:true})},
 {title:'A small tool when it helps',note:'A native iMessage poll. Vote for more than one option, toggle votes off, or add an option.',html:()=>chat(stamp('Friday 4:06 PM')+msg('we’re figuring out what to do. i hate picking a first date',true)+msg('what would feel easiest? you can pick a few')+poll()+msg('coffee and a walk. easy exit if it’s awkward lol',true)+msg('and you can keep walking if it isn’t'))},
 {title:'Voice, when the moment calls for it',note:'Play a sample voice note. The later call offer remains separate and needs an explicit yes. Local voice sample; no network playback.',html:()=>chat(stamp('Saturday 1:28 PM')+msg('leaving in 10. give me a tiny pep talk',true)+audio()+msg('“you’re meeting a person not defending a thesis” 😭 okay needed that',true)+msg('lol go. you already know how to talk to him')+'<div class="stamp" style="margin-top:22px">Saturday 5:42 PM</div>'+msg('back. it was good?? there’s a lot to unpack',true)+msg('want to talk it through on a call?')+msg('<button class="inline-call" data-call>yes call me</button>',true)+read)},
 {title:'It remembers the thing that mattered',note:'A remembered detail, an enthusiastic reply, and a familiar reaction GIF.',html:()=>chat(stamp('Sunday 11:03 AM')+msg('we got coffee and then walked for like 2 hours',true)+msg('how was the quiet?')+msg('comfortable actually. i didn’t feel like i had to perform',true)+msg('wait that’s exactly what you wanted 🥹')+msg('he asked to see me again 🥹',true)+msg('YAYYYY wait this is so cute 😭')+`<img class="sticker celebration-meme" src="assets/its-happening.gif" alt="Michael Scott: Oh my God, it’s happening!"><div class="sticker-still" role="img" aria-label="Celebration">YAYYYY ♡</div>`)},
 null
];
