// Authored Inyo experiences, presented locally with no delivery or backend calls.
const people=Object.fromEntries(['Leo','Kai','Daniel','Ethan'].map(name=>[name,profileData[name]]));
const explorations={
 fit:{title:'Fit check',description:'A look. A place. Your kind of night.',tint:'rose',rounds:[
 {title:'Which one feels<br>like you?',prompt:'No dress code. Pick the look you’d actually reach for.',limit:1,options:[['Off-duty','Shirt, denim, a little burgundy.'],['After hours','A blazer. A little more edge.'],['Slow Sunday','Soft layers. Go-anywhere shoes.']],chosen:[]},
 {title:'Okay, where<br>are we going?',prompt:'Same outfit. Three very different evenings.',limit:1,options:[['Coffee that runs late','One more story. One more block.'],['Dinner with no rush','Order something to share.'],['A little escape','Fresh air and a change of scene.']],chosen:[]},
 {title:'The best part<br>comes after.',prompt:'The plan’s over. What would make the night yours?',limit:1,options:[['Keep walking','Neither of us is in a hurry.'],['Home before eleven','A good night, and a little time for me.'],['Leave it open','Let’s see what we feel like.']],chosen:[]}]},
 future:{title:'Postcards from later',description:'Two good futures. Pick the small details you would keep.',tint:'clay',rounds:[
 {title:'An ordinary morning,<br>years from now.',prompt:'Which postcard would you rather wake up inside?',limit:1,options:[['A familiar little world','The same window. People who know my order.'],['A new view again','A different place. Something still to discover.']],chosen:[]},
 {title:'There is room<br>at the table.',prompt:'Which kind of togetherness belongs in that future?',limit:1,options:[['The door is often open','Friends, neighbours, a few extra chairs.'],['A few people, very close','A small world with room to breathe.']],chosen:[]},
 {title:'An unexpected<br>bit of freedom.',prompt:'What would you most want that freedom to buy?',limit:1,options:[['A softer landing','Stability. Fewer things to worry about.'],['More possibility','Time to try something I have put off.']],chosen:[]}]},
 friends:{title:'Small circle',description:'Make room for your people, then choose what keeps you close.',tint:'blue',rounds:[
 {title:'Plans, finally.',prompt:'Everyone’s free. Pick two plans for the group chat.',limit:2,options:[['A very long walk','No real destination.','talk'],['Dinner at mine','Something simple, stay a while.','sun'],['Find something new','A small adventure together.','kite'],['Parallel play','Our own things, same room.','moon']],chosen:[]},
 {title:'Someone new joins.',prompt:'A friend brought a friend. How do you find your way in?',limit:1,options:[['Ask them something','I am usually the first to open up.'],['Join an activity','Easier when there is something to do.'],['Let it happen slowly','Familiarity does the work.'],['Stay near my person','An introduction helps.']],chosen:[]},
 {title:'Rain check. Again.',prompt:'What would you text back? Go with your first instinct.',limit:1,options:[['Can we talk about it?','I want to clear the air.'],["Let’s try another day",'Keep it light for now.'],["I’ll take some space",'I need a little distance first.'],['Not sure what to say','I would need time to figure it out.']],chosen:[]}]}
};
const showcaseState={hearts:new Set(['Leo']),reactions:{Leo:'♥',Maya:'♥'},exploration:'fit',round:0,playback:0};
const library=()=>chat(stamp('Tuesday 8:14 PM')+msg('can we do something a little more fun? like outfits or life stuff',true)+msg('wait yes. build a look, dream up a future, or make plans with your people?')+`<div class="session-shelf">${['fit','future','friends'].map(key=>`<button class="shelf-card ${key}" data-explore="${key}"><span class="shelf-art">${key==='fit'?'<span class="fit-art" data-look="0"></span>':worldArt(key==='future'?1:2)}</span><span class="shelf-copy"><b>${explorations[key].title}</b><small>${explorations[key].description}</small><small class="link-host">joininyo.com</small></span></button>`).join('')}</div>`+`<div class="library-result" aria-live="polite" hidden></div>`);
const extras=[
 {title:'A few people, together.',html:()=>chat(stamp('Thursday 6:10 PM')+msg('okay, show me a few people?',true)+albumMarkup()+msg('leo 👀',true)+msg('heart anyone you’d like to meet. i’ll check if it’s mutual'),{cls:'deck-phone'})},
 {title:'There’s more to you than dating',html:library},
 {title:'Your everyday edit',html:()=>session(0,explorations.fit.rounds,explorations.fit.title)},
 {title:'Being known includes being corrected',html:()=>chat(stamp('Monday 9:42 AM')+msg('so, more of a quiet person?',false).replace('data-reactable=','id="memory-source" data-reactable=')+`<div class="reply-context"><button data-jump-source="memory-source"><small>Inyo</small>so, more of a quiet person?</button></div>`+msg('only when i’m comfortable. with my friends i’m actually so loud lol',true)+msg('ah, that’s different. comfortable silence, not a quiet personality')+msg('yes exactly. remember it that way',true,'♥')+msg('got it. <strong>comfortable silence</strong>, with plenty to say when you feel like it.'))},
 {title:'A follow-up worth getting',html:()=>chat(stamp('Monday 7:06 PM')+msg('did you two ever pick a second-date plan?')+msg('yes! dinner friday. i’m trying not to overthink it',true)+msg('what part are you turning over?')+msg('what if the first time was just lucky',true)+msg('then friday is a chance to learn a little more. it doesn’t have to prove anything yet')+msg('okay. that helps',true,'♥'))}
];
function syncDeck(){
 document.querySelectorAll('[data-person]').forEach(card=>{const parent=card.parentElement;parent.querySelector('.heart')?.remove();const reaction=showcaseState.reactions[card.dataset.person];if(reaction){const badge=document.createElement('span');badge.className='heart';badge.dataset.value=reaction;badge.textContent=reaction;badge.setAttribute('aria-label',reaction==='♥'?'Liked this profile':reaction+' reaction');parent.append(badge);}});
 const count=showcaseState.hearts.size,panel=document.querySelector('#selection-summary');if(panel)panel.textContent=count?`${count} ${count===1?'person':'people'} hearted · introductions still need mutual interest`:'Choose one, a few, or none.';
 const liked=showcaseState.reactions.Leo==='♥';
 const browse=document.querySelector('#screen-21 .thread>.row.out:last-of-type .bubble');if(browse&&browse!==document.querySelector('#screen-21 .thread>.row.out .bubble'))browse.textContent=liked?'leo 👀':'still looking 👀';
 const intro=document.querySelector('#screen-8 .thread>.row .bubble');if(intro)intro.textContent=liked?'leo caught your eye 👀':'want a closer look at leo?';
 const rows=document.querySelectorAll('#screen-9 .thread>.row .bubble');if(rows.length){rows[0].textContent=liked?'got your heart on leo’s card :)':'heart his card if you want an intro. i’ll check with him too';rows[1].textContent=liked?'yeah, i’d like to meet him':'i’ll leave it for now';rows[2].textContent=liked?'on it. i’ll check with him too':'of course. take your time';}
}
function renderExploration(){const data=explorations[showcaseState.exploration],host=document.querySelector('#screen-23');if(!host)return;host.querySelector('.phone').outerHTML=session(showcaseState.round,data.rounds,data.title);const title=host.querySelector('.frame-title');if(title)title.lastChild.textContent=data.title;const phone=host.querySelector('.phone');phone.dataset.exploration=showcaseState.exploration;phone.dataset.tint=data.tint;phone.querySelectorAll('[data-go]').forEach(b=>{b.removeAttribute('data-go');b.dataset.exploreClose='';});const next=phone.querySelector('[data-next]');next.removeAttribute('data-next');next.dataset.exploreNext='';const skip=phone.querySelector('.skip');skip.removeAttribute('data-explore-close');skip.dataset.exploreSkip='';next.disabled=data.rounds[showcaseState.round].chosen.length!==data.rounds[showcaseState.round].limit;screens[22].title=data.title;}
function finishExploration(returnToChat=false){if(showcaseState.exploration==='fit'&&!returnToChat){renderFitResult();return;}const data=explorations[showcaseState.exploration],labels=data.rounds.flatMap(r=>r.chosen.map(i=>r.options[i][0]));const result=document.querySelector('.library-result');if(result){result.hidden=false;result.replaceChildren();const box=document.createElement('div');box.innerHTML=receipt();box.querySelector('.receipt p').textContent=data.title+' is saved.';const reflection=document.createElement('div');reflection.className='session-reflection';reflection.textContent=labels.length?(showcaseState.exploration==='fit'?`okay this is a whole little evening 🥹 what part feels most like you?`:showcaseState.exploration==='future'?`“${labels[0]}” 👀 what’s one little piece of that you’d want right now?`:`“${labels[0]}” — who came to mind when you picked that?`):'saved. we can leave those questions open :)';if(showcaseState.exploration==='fit'&&labels.length){const card=document.createElement('div');card.className='fit-saved-board';card.innerHTML=fitKeepsake(data.rounds);result.append(card);}result.append(box,reflection);}go(22);requestAnimationFrame(()=>{const thread=result?.closest('.thread');if(thread)thread.scrollTo({top:thread.scrollHeight,behavior:'smooth'});});}
function cancelPlayback(){showcaseState.playback++;document.querySelectorAll('[data-replay-hidden]').forEach(x=>{x.hidden=false;x.removeAttribute('data-replay-hidden')});document.querySelectorAll('.typing-indicator').forEach(x=>x.remove());const b=document.querySelector('[data-play-conversation]');if(b)b.textContent='Replay conversation';if(typeof state!=='undefined')applyWall();}
async function replayConversation(){const thread=document.querySelector('article.current .thread');if(!thread)return;cancelPlayback();if(matchMedia('(prefers-reduced-motion: reduce)').matches){announce('Conversation is shown with reduced motion.');return;}const token=showcaseState.playback;if(state.current===18)thread.closest('.phone').dataset.background='default';const messages=[...thread.children].filter(x=>!x.hidden&&!x.classList.contains('transcript-history'));thread.scrollTop=0;messages.forEach(x=>{if(!x.hidden){x.hidden=true;x.dataset.replayHidden='true'}});document.querySelector('[data-play-conversation]').textContent='Show all messages';const sleep=ms=>new Promise(r=>setTimeout(r,ms));for(const item of messages){if(!item.hasAttribute('data-replay-hidden'))continue;if(token!==showcaseState.playback)return;if(item.classList.contains('row')&&!item.classList.contains('out')){const typing=document.createElement('div');typing.className='typing-indicator';typing.setAttribute('aria-label',(item.previousElementSibling?.classList.contains('speaker')?item.previousElementSibling.textContent:'Inyo')+' is typing');typing.innerHTML='<i></i><i></i><i></i>';item.before(typing);await sleep(530);typing.remove();}else if(!item.classList.contains('stamp')&&!item.classList.contains('speaker'))await sleep(270);if(token!==showcaseState.playback)return;item.hidden=false;item.removeAttribute('data-replay-hidden');if(item.dataset.backgroundEvent)thread.closest('.phone').dataset.background=item.dataset.backgroundEvent;if(state.current===1&&item.querySelector('em'))effect(thread.closest('.phone'));thread.scrollTop=thread.scrollHeight;}document.querySelector('[data-play-conversation]').textContent='Replay conversation';}
function showcaseClick(e){if(albumClick(e))return true;const b=e.target.closest('button');if(!b)return false;
 if(b.hasAttribute('data-fit-return')){finishExploration(true);return true;}
 if(b.hasAttribute('data-fit-edit')){showcaseState.round=0;renderExploration();return true;}
 if(b.hasAttribute('data-round-back')){const phone=b.closest('.phone');if(phone.dataset.exploration){showcaseState.round=Math.max(0,showcaseState.round-1);renderExploration();}else go(Number(phone.dataset.round)+3);return true;}
 if(b.hasAttribute('data-change-photo')){document.querySelector('#profile-photo').click();return true;}
 if(b.hasAttribute('data-play-conversation')){if(document.querySelector('[data-replay-hidden]'))cancelPlayback();else replayConversation();return true;}
 if(b.dataset.jumpSource){document.getElementById(b.dataset.jumpSource)?.focus();return true;}
 if(b.dataset.explore){showcaseState.exploration=b.dataset.explore;showcaseState.round=0;renderExploration();go(23);return true;}
 const phone=b.closest('[data-exploration]');if(!phone)return false;const data=explorations[showcaseState.exploration],r=data.rounds[showcaseState.round];
 if(b.classList.contains('choice')){const i=Number(b.dataset.choice);if(r.chosen.includes(i))r.chosen=r.chosen.filter(x=>x!==i);else if(r.limit===1)r.chosen=[i];else if(r.chosen.length<r.limit)r.chosen.push(i);else{announce('Choose up to '+r.limit+'. Deselect one to change your answer.');return true;}phone.querySelectorAll('.choice').forEach((c,i)=>{c.classList.toggle('selected',r.chosen.includes(i));c.setAttribute('aria-pressed',r.chosen.includes(i))});phone.querySelector('.count').textContent=r.chosen.length+' of '+r.limit+' selected';phone.querySelector('[data-explore-next]').disabled=r.chosen.length!==r.limit;refreshGame(phone);return true;}
 if(b.hasAttribute('data-explore-close')){go(22);return true;}
 if(b.hasAttribute('data-explore-next')||b.hasAttribute('data-explore-skip')){if(b.hasAttribute('data-explore-skip'))r.chosen=[];if(showcaseState.round===2)finishExploration();else{showcaseState.round++;renderExploration();}return true;}
 return false;
}

let photoRequest=0;
document.addEventListener('change',async e=>{
 if(e.target.id!=='profile-photo')return;const id=++photoRequest,file=e.target.files?.[0];if(!file)return;
 const line=document.querySelector('.save-line'),save=document.querySelector('#profile-form [type=submit]');
 if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){line.textContent='Choose a JPG, PNG or WebP under 10 MB.';e.target.value='';save.disabled=false;return;}
 const url=URL.createObjectURL(file),preview=new Image();save.disabled=true;line.textContent='Opening photo…';
 try{preview.src=url;await preview.decode();if(id!==photoRequest){URL.revokeObjectURL(url);return;}
  if(showcaseState.photo&&showcaseState.photo!==state.profilePhoto)URL.revokeObjectURL(showcaseState.photo);
  showcaseState.photo=url;document.querySelector('.editor-photo>img').src=url;line.textContent='Photo ready. Save changes to use it.';
 }catch{URL.revokeObjectURL(url);if(id===photoRequest)line.textContent='That image couldn’t open. Try another photo.';}
 finally{if(id===photoRequest){save.disabled=false;e.target.value='';}}
});

// Drag a card into the scene, or tap it. Both use the same selection handler.
document.addEventListener('dragstart',e=>{const choice=e.target.closest('.choice[draggable=true]');if(!choice)return;e.dataTransfer.setData('text/plain',choice.dataset.choice);e.dataTransfer.effectAllowed='copy';choice.closest('.phone').classList.add('dragging-choice');});
document.addEventListener('dragover',e=>{if(e.target.closest('[data-drop-zone]')&&e.target.closest('.dragging-choice')){e.preventDefault();e.dataTransfer.dropEffect='copy';}});
document.addEventListener('drop',e=>{const phone=e.target.closest('.dragging-choice');if(!phone||!e.target.closest('[data-drop-zone]'))return;e.preventDefault();const i=e.dataTransfer.getData('text/plain');const choice=[...phone.querySelectorAll('.choice')].find(x=>x.dataset.choice===i);if(choice&&!choice.classList.contains('selected'))choice.click();phone.classList.remove('dragging-choice');});
document.addEventListener('dragend',()=>document.querySelectorAll('.dragging-choice').forEach(p=>p.classList.remove('dragging-choice')));
